training:
  output_dir: "./models"
  num_train_epochs: 3
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  learning_rate: 0.0005
  weight_decay: 0.01
  warmup_steps: 100
  logging_steps: 50
  eval_steps: 100
  save_steps: 500
  save_total_limit: 2
  eval_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_f1"
  greater_is_better: true
  report_to: null

data:
  train_file: "data/FinTech-PII_MD/synthetic_moldova_pii_data.json"
  validation_split: 0.2
  test_split: 0.1
  max_length: 512
